/**
 * Generates dist/tokens.css (CSS custom properties) and dist/tokens.d.ts from
 * src/tokens.json. Run via `npm run tokens:build`. Never hand-edit dist/.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(
  await import('node:fs/promises').then((fs) =>
    fs.readFile(resolve(here, 'src/tokens.json'), 'utf8')
  )
);

const lines = [
  '/* Generated by packages/tokens/build.mjs - do not edit by hand. */',
  ':root {'
];

for (const [key, def] of Object.entries(tokens.color)) {
  lines.push(`  --color-${key.replace(/_/g, '-')}: ${def.value}; /* ${def.name} */`);
}
for (const [key, value] of Object.entries(tokens.space)) {
  lines.push(`  --space-${key}: ${value};`);
}
for (const [key, value] of Object.entries(tokens.radius)) {
  lines.push(`  --radius-${key}: ${value};`);
}
for (const [key, value] of Object.entries(tokens.shadow)) {
  lines.push(`  --shadow-${key}: ${value};`);
}
for (const [key, value] of Object.entries(tokens.motion)) {
  lines.push(`  --motion-${key}: ${value};`);
}
lines.push(`  --font-display: "${tokens.typography.display.family}", ${tokens.typography.display.fallback};`);
lines.push(`  --font-body: "${tokens.typography.body.family}", ${tokens.typography.body.fallback};`);
lines.push(`  --leading-body: ${tokens.typography.body.leading};`);
lines.push(`  --tracking-display: ${tokens.typography.display.tracking};`);
for (const [key, def] of Object.entries(tokens.typography.scale)) {
  lines.push(`  --type-${key.replace(/_/g, '-')}: ${def.size};`);
}
lines.push('}');

const dist = resolve(here, 'dist');
mkdirSync(dist, { recursive: true });
writeFileSync(resolve(dist, 'tokens.css'), lines.join('\n') + '\n');

const dts = [
  '// Generated by packages/tokens/build.mjs - do not edit by hand.',
  `export declare const colors: Record<${Object.keys(tokens.color).map((k) => `'${k}'`).join(' | ')}, string>;`,
  'export declare const space: Record<string, string>;',
  'export declare const radius: Record<string, string>;',
  'declare const tokens: unknown;',
  'export default tokens;'
];
writeFileSync(resolve(dist, 'tokens.d.ts'), dts.join('\n') + '\n');

console.log(`tokens: wrote ${Object.keys(tokens.color).length} colour tokens to dist/tokens.css`);
